export const BLOGDATAS = [
  {
    id: 0,
    name: "Que sont les omégas 3?",
    image: "images/omega.webp",
    alt: "image omega",
    text:
      "On en parle beaucoup, mais que sont-ils exactement ? A quoi servent-ils ? Où les trouve-t-on ?" +
      "Les omégas 3 sont des acides gras à longues chaines avec plusieurs doubles liaisons. Ce sont...",
    completText: [
      "On en parle beaucoup, mais que sont-ils exactement ? A quoi servent-ils ? Où les trouve-t-on ?",
      "Les omégas 3 sont des acides gras à longues chaines avec plusieurs doubles liaisons. Ce sont des acides gras polyinsaturés. Le précurseur en est l’acide alpha linolénique : il se transforme grâce à différentes enzymes en EPA et DHA, qui sont les omégas 3." +
        "Nos membranes cellulaires sont formées de deux couches d’acides gras. Si nous manquons d’omégas 3, elles seront plus rigides, alors notre réponse inflammatoire lors d’attaques virales, bactériennes… sera exagérée.",
      "C’est pourquoi les omégas 3 sont si importants pour nous protéger des problèmes cardiovasculaires. Ils ont un rôle « antiinflammatoire ». Ils sont prioritaires pour nos yeux, notre peau, et notre cerveau….",
      "  L’acide alpha linolénique se trouve dans les végétaux : colza, lin, caméline, noix, mâche, roquette, pourpier, jeunes pousses d’épinard, algues." +
        "",
      "L’EPA et DHA se trouvent dans les poissons gras : sardines, maquereaux, saumon, thon, algues et dans les produits provenant de la filière bleu-blanc-cœur (Cf. «Au petit déjeuner, on nourrit ses neurones »)." +
        "",
      "Dans beaucoup de situations  (enfant de moins de 18 mois, adulte de plus de 70 ans, dysbiose, stress, insulinorésistance, diabète, prises de certains médicaments…), une des enzymes qui transforme l’acide alpha linolénique en omégas 3 ne fonctionne pas bien. C’est pourquoi il est important d’apporter à notre corps chaque jour des sources végétales du précurseur, et régulièrement des sources animales d’omégas3.",
    ],
  },
  {
    id: 1,
    name: "Qu’est-ce que la micronutrition ?",
    image: "images/micronutrition.webp",
    alt: "image micronutrition",
    text: "La Micronutrition, une approche de la nutrition médicalisée adaptée à chacun…La Micronutrition consiste à satisfaire les besoins en micronutriments de l’individu, par une alimentation...",
    // completText: [<p>text1</p>,<p>text2</p>],
    completText: [
      "La Micronutrition, une approche de la nutrition médicalisée adaptée à chacun...\n",
      "" +
        "La Micronutrition consiste à satisfaire les besoins en micronutriments de l’individu, par une alimentation diversifiée, associée si nécessaire à une complémentation personnalisée. Elle trouve ses fondements dans les recherches effectuées sur les liens avérés entre alimentation, santé et prévention.",
      "Pourquoi la Micronutrition plutôt que la nutrithérapie ?",
      "La Micronutrition s’intéresse à l’impact des micronutriments sur la santé et vise à optimiser le statut en micronutriments de l’organisme de manière individualisée. Elle choisit donc de regarder les précieuses molécules qui se trouvent dans notre assiette et la façon dont notre organisme les utilise. Elle prend toute sa dimension aujourd’hui avec une alimentation qui se caractérise par l’augmentation de l’apport calorique au détriment de la densité en micronutriments. C’est ce qu’on appelle d’ailleurs « les calories vides ».",
      "Les MICROnutriments : des composés MEGAimportants",
      "Schématiquement, on retrouve dans nos aliments :",
      "",
      "- des macronutriments qui fournissent l’énergie et la force nécessaires à l’organisme. Ce sont les lipides, les glucides et les protéines.",
      "- des micronutriments qui ne jouent aucun rôle énergétique mais dont le rôle est fondamental pour le fonctionnement de l’ensemble des métabolismes. Ce sont les vitamines, minéraux, oligo-éléments, acides gras essentiels mais aussi les flavonoïdes, acides aminés, probiotiques ...",
      "  Tous ces éléments donnent la valeur nutritionnelle de l’assiette.",
    ],
  },
  {
    id: 2,
    name: "Quand faire appel à la micronutrition ?",
    image: "images/appel-micronutrition.webp",
    alt: "image appel micronutrition",
    text: "Parce qu’elle n’est pas réservée à une population particulière mais au contraire adaptée pour apporter des solutions personnalisées à chaque période de la vie, la micronutrition s’adresse à tous ceux...",
    completText: [
      "  Parce qu’elle n’est pas réservée à une population particulière mais au contraire adaptée pour apporter des solutions personnalisées à chaque période de la vie, la micronutrition s’adresse à tous ceux qui :",
      "• souffrent d’inconfort digestif, du syndrome du colon irritable, de colite, de troubles de la détoxication,",
      "• rencontrent des problèmes de concentration, de mémoire, de sommeil,",
      "• se plaignent de douleurs musculaires, articulaires ou rhumatismales,",
      "• sont particulièrement sensibles aux refroidissements hivernaux, aux allergies",
      "• se sentent fatigués, déprimés,",
      "• rencontrent des désordres hormonaux (cycles irréguliers, ménopause, troubles de la prostate),",
      "• souffrent de syndrome métabolique, diabète, obésité,",
      "• souhaitent affiner leur silhouette tout en restant en forme et en bonne santé,",
      "• désirent optimiser leurs performances sportives,",
      "• souhaitent une alimentation équilibrée durant leur grossesse pour leur bien-être et celui du bébé,",
      "• souhaitent favoriser la croissance physique, intellectuelle et émotionnelle de leurs enfants et adolescents,",
      "• souhaitent vivre en forme pleinement et le plus longtemps possible…",
      "        … quelques situations, entre-autres, pour lesquelles la micronutrition s’avère efficace et sans effets secondaires désagréables.",
    ],
    // completText: ["text1","text2"],
  },
  {
    id: 3,
    name: "Qu’est-ce que la dysbiose ?",
    image: "images/omega.webp",
    alt: "image omega",
    text: "La dysbiose (par opposition à l’eubiose) est le nom donné à « la guerre dans l’intestin ». Les bactéries « méchantes » et autres microorganismes (tels que levures, parasites) ont pris le dessus sur...",
    completText: [
      "La dysbiose (par opposition à l’eubiose) est le nom donné à « la guerre dans l’intestin ». Les bactéries « méchantes » et autres microorganismes (tels que levures, parasites) ont pris le dessus sur nos bactéries amies. Cette dysbiose est certainement à l’origine de toutes maladies chroniques (syndrome métabolique, diabète, obésité, problèmes cardiovasculaires, maladies auto-immunes, allergies, fatigue chronique, dépression, fibromyalgie, problème de peau…). La « mal bouffe », le stress, la prise de médicaments sont souvent des facteurs responsables ou déclenchants. C’est pourquoi, il faut veiller à bien nourrir le microbiote avec une alimentation saine, la moins transformée possible (partir de l’aliment brut et le cuisiner soi-même), très variée, riche en micronutriments (avec légumes et fruits de saison bio), la moins raffinée possible, et réapprendre à bien mastiquer pour permettre une bonne digestion. Une éviction alimentaire sera nécessaire dans les cas d’hypersensibilité à certains aliments (gluten, protéines de lait de vache, lactose, œufs, Fodmap…).",
    ],
    // completText: ["text1","text2"],
  },
  {
    id: 4,
    name: "Comment revenir à la paix dans l’intestin ?",
    image: "images/paix-intestin.webp",
    alt: "image paix intestin",
    text: "Lorsque la dysbiose est installée, le changement d’alimentation, l’exclusion d’aliments créant une hypersensibilité ne seront, le plus souvent, pas suffisant pour rétablir la paix. Il faut réensemencer...",
    completText: [<p>text1</p>, <p>text2</p>],
  },
  {
    id: 5,
    name: "Qu’est-ce que l’hyperperméabilité intestinale ?",
    image: "images/omega.webp",
    alt: "omega",
    text: "L’hyperperabilité intestinale représente l’ouverture des jonctions serrées qui se situent entre chaque cellule de l’intestin. Ces jonctions, qui peuvent être représentées comme des portes...",
    // completText: ["text1", "text2"],
    completText: [<p>text1</p>, <p>text2</p>],
  },
  {
    id: 6,
    name: "Que se passe-t-il quand on manque de certains micronutriments ?",
    image: "images/manque-micronutriments.webp",
    alt: "legumineuse",
    text: "L’organisme fonctionne alors en mode « économie » en dépensant un minimum d’énergie et en stockant les moindres excès. C’est souvent le cas après des...",
    completText: [<p>text1</p>, <p>text2</p>],
  },
  {
    id: 7,
    name: "Au petit-déjeuner on nourrit les neurones",
    image: "images/petit-dej.webp",
    alt: "image oeuf petit dej",
    text: "Objectif du premier repas de la journée : fournir l’énergie nécessaire pour tenir toute la matinée de travail et permettre à l’influx nerveux de se propager le long de nos...",
    completText: [<p>text1</p>, <p>text2</p>],
  },
  {
    id: 8,
    name: "Huiles toxiques ",
    image: "images/huiles-toxiques.webp",
    alt: "image huiles toxiques",
    text: "Un article du Canard enchainé * nous en apprend de belles sur les huiles végétales.On se doutait bien que les processus de transformation industrielle des huiles...",
    completText: [<p>text1</p>, <p>text2</p>],
  },
];
